name: Build and push container images to quay.io registry
on:
  push:
    branches:
      - master
  schedule:
      - cron: '0 1 * * 3'
jobs:
  build-and-push:
    if: github.repository_owner == 'sclorg'
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: "1.20"
            tag: "c9s"
            dockerfile: "Dockerfile.c9s"
            registry_namespace: "sclorg"
            quayio_username: "QUAY_IMAGE_SCLORG_BUILDER_USERNAME"
            quayio_token: "QUAY_IMAGE_SCLORG_BUILDER_TOKEN"
            image_name: "nginx-120-c9s"

          - version: "1.22-micro"
            tag: "c9s"
            dockerfile: "Dockerfile.c9s"
            registry_namespace: "sclorg"
            quayio_username: "QUAY_IMAGE_SCLORG_BUILDER_USERNAME"
            quayio_token: "QUAY_IMAGE_SCLORG_BUILDER_TOKEN"
            image_name: "nginx-122-micro-c9s"

          - version: "1.24"
            tag: "fedora"
            dockerfile: "Dockerfile.fedora"
            registry_namespace: "fedora"
            quayio_username: "QUAY_IMAGE_FEDORA_BUILDER_USERNAME"
            quayio_token: "QUAY_IMAGE_FEDORA_BUILDER_TOKEN"
            image_name: "nginx-124"

          - version: "1.26"
            tag: "fedora"
            dockerfile: "Dockerfile.fedora"
            registry_namespace: "fedora"
            quayio_username: "QUAY_IMAGE_FEDORA_BUILDER_USERNAME"
            quayio_token: "QUAY_IMAGE_FEDORA_BUILDER_TOKEN"
            image_name: "nginx-126"

          - version: "1.24"
            tag: "c9s"
            dockerfile: "Dockerfile.c9s"
            registry_namespace: "sclorg"
            quayio_username: "QUAY_IMAGE_SCLORG_BUILDER_USERNAME"
            quayio_token: "QUAY_IMAGE_SCLORG_BUILDER_TOKEN"
            image_name: "nginx-124-c9s"

    steps:
      - name: Build and push to quay.io registry
        uses: sclorg/build-and-push-action@main
        with:
          registry: "quay.io"
          registry_namespace: ${{ matrix.registry_namespace }}
          registry_username: ${{ secrets[matrix.quayio_username] }}
          registry_token: ${{ secrets[matrix.quayio_token] }}
          dockerfile: ${{ matrix.version }}/${{ matrix.dockerfile }}
          tag: ${{ matrix.tag }}
          image_name: ${{ matrix.image_name }}
          readme: "${{ matrix.version }}/README.md"
          quay_application_token: ${{ secrets.QUAY_IMAGE_SCLORG_UPDATE_DESC }}
