name: Build and push container images to quay.io registry
on:
  push:
    branches:
      - master
  schedule:
      - cron: '0 1 * * 3'
jobs:
  build-and-push:
    if: github.repository_owner == 'sclorg'
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile_path: "1.20"
            dockerfile: "Dockerfile"
            registry_namespace: "centos7"
            quayio_username: "QUAY_IMAGE_BUILDER_USERNAME"
            quayio_token: "QUAY_IMAGE_BUILDER_TOKEN"
            tag: "centos7"
            suffix: "centos7"
          - dockerfile_path: "1.20"
            dockerfile: "Dockerfile.c9s"
            registry_namespace: "sclorg"
            quayio_username: "QUAY_IMAGE_SCLORG_BUILDER_USERNAME"
            quayio_token: "QUAY_IMAGE_SCLORG_BUILDER_TOKEN"
            tag: "c9s"
            suffix: "c9s"
          - dockerfile_path: "1.22"
            dockerfile: "Dockerfile.fedora"
            registry_namespace: "fedora"
            quayio_username: "QUAY_IMAGE_FEDORA_BUILDER_USERNAME"
            quayio_token: "QUAY_IMAGE_FEDORA_BUILDER_TOKEN"
            tag: "fedora"
          - dockerfile_path: "1.24"
            dockerfile: "Dockerfile.fedora"
            registry_namespace: "fedora"
            quayio_username: "QUAY_IMAGE_FEDORA_BUILDER_USERNAME"
            quayio_token: "QUAY_IMAGE_FEDORA_BUILDER_TOKEN"
            tag: "fedora"
          - dockerfile_path: "1.22-micro"
            dockerfile: "Dockerfile.fedora"
            registry_namespace: "fedora"
            quayio_username: "QUAY_IMAGE_FEDORA_BUILDER_USERNAME"
            quayio_token: "QUAY_IMAGE_FEDORA_BUILDER_TOKEN"
            tag: "fedora"

    steps:
      - name: Build and push to quay.io registry
        uses: sclorg/build-and-push-action@v4
        with:
          registry: "quay.io"
          registry_namespace: ${{ matrix.registry_namespace }}
          registry_username: ${{ secrets[matrix.quayio_username] }}
          registry_token: ${{ secrets[matrix.quayio_token] }}
          dockerfile: ${{ matrix.dockerfile }}
          docker_context: ${{ matrix.dockerfile_path }}/..
          dockerfile_path: ${{ matrix.dockerfile_path }}
          tag: ${{ matrix.tag }}
          suffix: ${{ matrix.suffix }}
